### ISSUE TITLE
Add third garden to the react mockup

### ISSUE THREAD

**Issue by philipmjohnson** [geogardenclub/geogardenclub.github.io#12]
@Jennacd was recently contacted by a local gardener who wants their garden implemented in the public view. 

Working on this task has the potential to reveal new requirements for GGC in general and the alpha release in particular.

**Comment by Jennacd** [comment]
Please add this garden to the drop down: 

https://agilegardenclub.com/public-garden/?name=32pcu61yt

@philipmjohnson

**Comment by philipmjohnson** [comment]
@Jennacd Done.
