### ISSUE TITLE
Write user guide

### ISSUE THREAD

**Issue by philipmjohnson** [geogardenclub/geogardenclub.github.io#15]
We need a new section in geogardenclub.com called "User Guide". It should provide a tutorial guide to the system, suitable for new users to get started and for experienced users to obtain help on features they come across. 

Some of the sections in the User Guide could include:

- [x]  Overview.  Why use GGC? What are the benefits?
- [x] Downloading.  The steps involved with getting GGC on your phone. This is fairly complicated during the beta test period, so we will want to provide step-by-step instructions with screen shots. 
- [x] Registration. OK, it's on your phone. Step by step instructions for initial signup, including the "onboard screen" process.
- [x] Guided Tour.  In this section, briefly run through the Index Screens and how to navigate through the system. Includes clicking on badges to navigate to details. This orients new users to the major entities in the system. 
- [x] Your first garden. Walk through the steps involved in creating a garden. Assume that the vendors, crops, and varieties already exist. Include adding another user as an editor, and what that means.
- [x] Adding Vendors, Crops, Varieties.  Explain how to augment the system if you need to refer to a Vendor, Crop, or Variety that does not already exist.
- [x] Observations.  Explain why and how to add Observations.
- [x] Badges. Explain why and how to obtain Badges.
- [x] Outcomes. When and how to record outcomes
- [x] Tasks. Why and how to use tasks.
- [x] Seeds. How and why to use them.
- [x]  Chat Rooms. How and why.
- [x] "Unknown" varieties - how they are represented
- [x] Gold varieties
- [x] Seed details: What it means when a Seed start date says N/A (because they are from vendors)
- [x] Add a section to explain how to accommodate different planting scenarios and definition of "Used Greenhouse"?
- [x] Explain how to add perennials as a planting (start date = first harvest date, end date = last harvest date, so that harvest are tracked.
- [ ] Explain how to decide whether to make one or multiple gardens for users with large garden spaces or different garden areas
- [ ] Explain how to register and set up a garden for a group/community/school garden situation
- [x] How to distinguish something you planted as a purchased seedling vs direct seeding. (start date = transplant date)
- [x] Options if you want to add plantings but don't know the bed yet.
- [x] Design Innovations: comment out public view section

**Comment by AbdoALPOP** [comment]
Hello @philipmjohnson ,
I am prepared to use mkdocs.org and material theme to create and publish this guide online.
Here are some samples:
----
https://docs.redstone.finance/docs/introduction
https://help.dev.washmaster.ch/
https://documentation-orhp.vercel.app/
https://docs.lucidya.com/
https://docs.salla.dev/

Please contact me: abdoprogrammer55@gmail.com

**Comment by Jennacd** [comment]
## Which varieties of corn grow best in my area?

## When I grew beets two years ago, how did that work out?

## I had a great crop of beets last year, how can I replicate that success?

## Does anyone have basil seeds to share?

## Who in my chapter is really good at growing tomatoes?

## Who might I contact for advice on growing a pesticide-free garden?

## What cover crops are being used in my chapter?

## Are there gardens using native plants in my chapter?

## How many days do I need to keep this plant in the garden before pulling it to replace with another plant if I want to harvest seeds?

## How can I replicate the success of another gardener in my chapter?

**Comment by philipmjohnson** [comment]
I think the user guide is good enough for now.
