### ISSUE TITLE
Document Beta Tester Feedback

### ISSUE THREAD

**Issue by Jennacd** [geogardenclub/geogardenclub.github.io#16]
Please do work in this issue-16

- Review feedback and add additional details for more complex features.  
- Create issues as appropriate.

- [ ] Krista (5/5) Whole bed and whole garden tasks that would be great to be able to assign to one's task list: spread lime, annual irrigation setup, mulching, weeding, fertilizing, spreading compost, trellissing, pruning (ex an entire bed of tomatoes with many varieites in it). Perhaps there is a way to create tasks that will go onto our task list that is separate from the system that connects tasks to the planting calendar.

**Comment by philipmjohnson** [comment]
Dev Guide now has beta test feedback
