### ISSUE TITLE
Create marketing plan

### ISSUE THREAD

**Issue by philipmjohnson** [geogardenclub/geogardenclub.github.io#21]
Here are some ideas for how to build our marketing plan:

* Research "digital marketing plan". I did a little and most of it was not helpful for us. But further digging might come up with something.
 
* Research "tik tok marketing", "instagram marketing",  "facebook marketing". See if we can find good exemplars of channels/users that we should emulate. Not necessarily gardening.

* Find gardening "influencers" (if they exist). We want to eventually contact them.

* Gardening publications (online or print). Find publications that do reviews of technologies. 

* Design other ways to acquire users. For example, farmers markets. I think these are called "channels"

Write up results as a chapter in the developers guide. 

I see the chapter being organized as follows:

Overview: Goal of the marketing plan.

Best Practices:  Provides a kind of tutorial on what a good digital/social media marketing plan consists of. Defines terms, metrics, etc.  Links to sites for further details. Kind of a "Marketing 101". 

Beta Test Marketing Plan:  For 2025, we are focusing just on Whatcom County, so the marketing plan will be "special". Describe what we will do to market to this audience, with dates etc. Who do we contact? Do we hand out merch? Are the competitions or prizes or other incentives? What constitutes success? The app will still be free.

Public Release Marketing Plan:  For 2026, we plan to go into general release as a paid, subscription-based product. I think there are two kinds of marketing: "global" and "new chapter". Global marketing might involve advertising, contact with influences, etc that is independent of the region. "New Chapter" marketing involves activities to bootstrap a chapter in a specific location.

**Comment by Jennacd** [comment]
Proposal from Audrey Madison:

[Audrey Madison Marketing Proposal.pdf](https://github.com/user-attachments/files/17880428/Audrey.Madison.Marketing.Proposal.pdf)
